<?php
namespace App\Helper;

class Trans
{   
    public static  function getLang()
    {
      return [
        ["Store Locator","Store Locator"],
        ["Location","Location"],
        ["Product","Product"],
        ["Enter city, State, or Zip","Enter city, State, or Zip"],
        ["Name Product","Name Product"],
        ["Find my location","Find my location"],
        ["Radius","Radius"],
        ["kilometers","kilometers"],
        ["miles","miles"],
        ["Reset","Reset"],
        ["Search","Search"],
        ["Store list","Store list"],
        ["result","result"],
        ["There is no store","There is no store"],
        ["is not found","is not found"],
        ["There is no store near with","There is no store near with"],
        ["There is no store contain product name is:","There is no store contain product name is:"],
        ["Contact with store","Contact with store"],
        ["Get directions","Get directions"],
        ["DRIVING","DRIVING"],
        ["TRANSIT","TRANSIT"],
        ["WALKING","BICYCLING"],
        ["BICYCLING","BICYCLING"],
        ["Your Location","Your Location"],
        ["Get Directions","Get Directions"],
        ["Description","Description"],
        ["Information of store","Information of store"],
        ["Monday","Monday"],
        ["Tuesday","Tuesday"],
        ["Wednesday","Wednesday"],
        ["Thursday","Thursday"],
        ["Friday","Friday"],
        ["Saturday","Saturday"],
        ["Sunday","Sunday"],
        ["Close","Close"],
        ["Opening hours","Opening hours"],
        ["Contact Us","Contact Us"],
        ["Full Name","Full Name"],
        ["Email","Email"],
        ["Telephone","Telephone"],
        ["Phone Number","Phone Number"],
        ["Phone No","Phone No"],
        ["Comment","Comment"],
        ["Address","Address"],
        ["Website","Website"],
        ["Toggle Street View","Toggle Street View"],
        ["Store Hours","Store Hours"],
        ["About","About"],
        ["Required Fields","Required Fields"],
        ["Submit","Submit"],
        ["name.required","Name field is required"],
        ["_token.required","Token field is required"],
        ["store_email.required","Email field is required"],
        ["store_email.email","Email must be a valid email address"],
        ["recipient.required","Recipient field is required"],
        ["recipient.email","Recipient must be a valid email address"],
        ["comment.required","Comment field is required"],
        ["recaptcha.required","Recaptcha field is required"],
        ["email.failed","Message sending failed."],
        ["email.success","Your message has been sent successfully!"],
        ["please_enter","Please enter a location."],
        ["no_store","There is no store"],
        ["no_result","No results found"],
        ["geocoder_failed","Geocoder failed due to: "],
        ["address_null"," is not found"],
        ["store_near","There is no store near with "],
        ["link_detail","View Details"],
        ["Search Radius","Search Radius"],
        ["Filter Tags:","Filter Tags:"],
        ["Get Direction","Get Direction"],

       ];
    }
}